influence4 <- read.csv("../data/data.csv", header=T)
attach(influence4)

model.1 <- lm(formula = Stack.Loss ~ poly(Air.Flow, 2) + Water.Temp)
summary(model.1)

model.2 <- lm(formula = Stack.Loss ~ poly(Air.Flow, 2) + Water.Temp,subset=c(1:20))
summary(model.2)

model.3 <- lm(formula = Stack.Loss ~ poly(Air.Flow, 2) + Water.Temp,subset=c(c(1:3),c(5:20)))
summary(model.3)

model.4 <- lm(formula = Stack.Loss ~ poly(Air.Flow, 2) + Water.Temp,subset=c(c(1),c(3),c(5:20)))
summary(model.4)

model.5 <- lm(formula = Stack.Loss ~ poly(Air.Flow, 2) + Water.Temp,subset=c(c(3),c(5:20)))
summary(model.5)

model.6 <- lm(formula = Stack.Loss ~ poly(Air.Flow, 2) + Water.Temp,subset=c(c(2),c(5:20)))
summary(model.6)

# cooks distance values
obs <- c(1:21)
a <- round(cooks.distance(model.1),3)
b <- round(cooks.distance(model.2),3)
b <- append(b,'*')
c <- round(cooks.distance(model.3),3)
c <- append(c,'*')
c <- append(c,'*',3)
d <- round(cooks.distance(model.4),3) 
d <- append(d,'*')
d <- append(d,'*',2)
d <- append(d,'*',1)
e <- round(cooks.distance(model.5),3)
e <- append(e,'*')
e <- append(e,'*',0)
e <- append(e,'*',1)
e <- append(e,'*',3)
f <- round(cooks.distance(model.6),3)
f <- append(f,'*')
f <- append(f,'*',0)
f <- append(f,'*',2)
f <- append(f,'*',3)

df1=data.frame('obs'=obs,'None'=a,'21'=b,'21,4'=c,'21,4,2'=d,'21,4,2,1'=e,'21,4,1,3'=f)
df1

# hatvalues
obs <- c(1:21)
a <- round(hatvalues(model.1),3)
b <- round(hatvalues(model.2),3)
b <- append(b,'*')
c <- round(hatvalues(model.3),3)
c <- append(c,'*')
c <- append(c,'*',3)
d <- round(hatvalues(model.4),3) 
d <- append(d,'*')
d <- append(d,'*',2)
d <- append(d,'*',1)
e <- round(hatvalues(model.5),3)
e <- append(e,'*')
e <- append(e,'*',0)
e <- append(e,'*',1)
e <- append(e,'*',3)
f <- round(hatvalues(model.6),3)
f <- append(f,'*')
f <- append(f,'*',0)
f <- append(f,'*',2)
f <- append(f,'*',3)

df2=data.frame('obs'=obs,'None'=a,'21'=b,'21,4'=c,'21,4,2'=d,'21,4,2,1'=e,'21,4,1,3'=f)
df2

# hatvalues
obs <- c(1:21)
a <- round(hatvalues(model.1),3)
b <- round(hatvalues(model.2),3)
b <- append(b,'*')
c <- round(hatvalues(model.3),3)
c <- append(c,'*')
c <- append(c,'*',3)
d <- round(hatvalues(model.4),3) 
d <- append(d,'*')
d <- append(d,'*',2)
d <- append(d,'*',1)
e <- round(hatvalues(model.5),3)
e <- append(e,'*')
e <- append(e,'*',0)
e <- append(e,'*',1)
e <- append(e,'*',3)
f <- round(hatvalues(model.6),3)
f <- append(f,'*')
f <- append(f,'*',0)
f <- append(f,'*',2)
f <- append(f,'*',3)

df2=data.frame('obs'=obs,'None'=a,'21'=b,'21,4'=c,'21,4,2'=d,'21,4,2,1'=e,'21,4,1,3'=f)
df2

# hatvalues
obs <- c(1:21)
a <- round(rstandard(model.1),2)
b <- round(rstandard(model.2),2)
b <- append(b,'*')
c <- round(rstandard(model.3),2)
c <- append(c,'*')
c <- append(c,'*',3)
d <- round(rstandard(model.4),2) 
d <- append(d,'*')
d <- append(d,'*',2)
d <- append(d,'*',1)
e <- round(rstandard(model.5),2)
e <- append(e,'*')
e <- append(e,'*',0)
e <- append(e,'*',1)
e <- append(e,'*',3)
f <- round(rstandard(model.6),2)
f <- append(f,'*')
f <- append(f,'*',0)
f <- append(f,'*',2)
f <- append(f,'*',3)

df3=data.frame('obs'=obs,'None'=a,'21'=b,'21,4'=c,'21,4,2'=d,'21,4,2,1'=e,'21,4,1,3'=f)
df3
# save files
write.csv(df1, "cooksdistance.csv", row.names=FALSE, quote=FALSE) 
write.csv(df2, "hatvalues.csv", row.names=FALSE, quote=FALSE) 
write.csv(df3, "studentresidual.csv", row.names=FALSE, quote=FALSE) 
